name: Auto Merge PRs

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened, ready_for_review]
  check_suite:
    types: [completed]
  status:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          # MERGE_LABELS: "auto-merge,!wip" # Example: only auto-merge when "auto-merge" label is present and "wip" label is not.
          MERGE_METHOD: "rebase" # Choose from merge, squash, or rebase.
          MERGE_COMMIT_MESSAGE: "pull-request-title" # Options: pull-request-title, pull-request-description, pull-request-title-and-description, or a custom message using variables.
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000" # Retry interval in milliseconds.
          MERGE_DELETE_BRANCH: "true" # Delete branch after merge.